FROM ros:humble
RUN apt update
RUN apt update
RUN apt-get install -y libjpeg-dev libjpeg8-dev libfreetype6-dev vim
RUN apt-get install -y ros-humble-diagnostic-updater 
RUN apt-get install  -y ros-humble-tf-transformations 
RUN apt install -y ros-humble-robot-localization

